export const messages = {
  username_req: 'Please type your Username (Hint: sometimes username is equal to email)',
  password_req: 'Please type your Password',
  problem_in_login_msg: 'Oops!\nthere is a problem with login!',
  enter_your_app_name_msg: 'Enter your app name',
  enter_your_ram_msg: 'Enter your ram (GB)',
  enter_your_core_msg: 'Enter your CPU (core)',
  enter_your_disk_msg: 'Enter your disk (GB)',
  enter_your_min_ram_per_instance_msg: 'Enter your min ram per instance',
  enter_your_max_ram_per_instance_msg: 'Enter your max ram per instance',
  enter_your_min_core_per_instance_msg: 'Enter your min core per instance',
  enter_your_max_core_per_instance_msg: 'Enter your max core per instance',
  enter_your_min_instance_msg: 'Enter your min instance',
  enter_your_max_instance_msg: 'Enter your max instance',
  enter_your_cmd_msg: 'Enter your cmd',
  enter_your_link_name_msg: 'Enter your link name',
  enter_your_link_alias_msg: 'Enter your link alias',
  enter_your_args_msg: 'Enter your arg',
  enter_your_git_username_msg: 'Enter your git username',
  enter_your_git_access_token_msg: 'Enter your git access token',
  enter_your_git_url_msg: 'Enter your git url',
  enter_your_image_name_msg: 'Enter your image name',
  enter_your_port_msg: 'Enter your port',
  enter_your_protocol_msg: 'Enter your protocol',
  enter_your_environment_key_msg: 'Enter your env key',
  enter_your_environment_value_msg: 'Enter your env value',
  enter_your_label_key_msg: 'Enter your label key',
  enter_your_label_value_msg: 'Enter your label value',
  click_here_to_login_msg: 'CLICK HERE TO LOGIN TO SAKKU!',
  w8_msg: 'Please wait...',
  abort_msg: 'Abort! :(',
  done_msg: 'Done! :)',
  exec_exit_msg: '\nEnding session\n',
  enter_your_instance_msg: 'Enter your the instance number you want',
  enter_your_check_point: 'Enter your check point for health check (default is /ping)',
  enter_your_response: 'Enter your response for health check',
  enter_your_scheme: 'Enter your scheme for health check (default is http)',
  loggedin: 'You are logged in.',
  tryToLog: 'Logging in to Sakku...',
  incorrect_credentials: 'Incorrect username or password.',
  unexpected: 'Unexpected Error',
  not_logged_in: 'You are not logged in. Please Login with your credentials',
  appIdName: 'Enter app id/name',
  enter_app_id: 'Enter app id',
  noInstance: 'There is no instance!',
  connectionSuccess: 'Connection established successfully.',
  connectionFail: 'Can not connect to remote host!',
  enter_username: 'Enter your username',
  environment_vars: 'Is there any/more environments (y or n)',
  labels: 'Is there any/more labels (y or n)',
  health_check: 'Is there any/more health checks (y or n)',
  args: 'Is there any/more args (y or n)',
  private_repo: 'Is it a private repository (y or n)',
  ports: 'Is there any/more ports (y or n)',
  enter_access_token: 'Enter your access token',
  app_add_success: 'Your app is successfully added.',
  enter_image_name: 'Enter your image name',
  enter_docker_file_address: 'Enter your docker file address (default is /DockerFile)',
  enter_branch_name: 'Enter your branch name (default is master)',
  more_tag: 'Is there any/more tags (y or n)',
  enter_tag: 'Enter your tag',
  more_build_args: 'Is there any/more build arguments (y or n)',
  enter_build_arg: 'Enter your build document',
  empty_list: 'Empty List',
  enter_col_email: 'Enter your collaborator\'s email',
  enter_col_image_reg: 'Enter your collaborator\'s image registry (Optional)',
  col_add_success: 'Collaborator added successfully.',
  col_edit_success: 'Collaborator edited successfully.',
  col_del_success: 'Collaborator deleted successfully.',
  enter_col_id: 'Enter your collaborator\'s id'
}
